# Generated by Django 5.2.5 on 2025-08-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('emailAdd', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.CharField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('ratingCount', models.IntegerField(default=0)),
                ('avgStars', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('tot_xpPts', models.IntegerField(default=0)),
                ('xpRank', models.CharField(default='Unranked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ImageField(blank=True, null=True, upload_to='user_verifyids/')),
                ('links', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'users_tbl',
                'managed': False,
            },
        ),
    ]
