# Generated by Django 5.2.4 on 2025-09-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenSkill',
            fields=[
                ('genSkills_id', models.AutoField(db_column='genskills_id', primary_key=True, serialize=False)),
                ('genCateg', models.CharField(db_column='gencateg', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'genskills_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecSkill',
            fields=[
                ('specSkills_id', models.AutoField(db_column='specskills_id', primary_key=True, serialize=False)),
                ('specName', models.CharField(db_column='speccateg', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'specskills_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('usercred_id', models.AutoField(db_column='usercred_id', primary_key=True, serialize=False)),
                ('credential_title', models.CharField(db_column='credential_title', max_length=150)),
                ('issuer', models.CharField(db_column='issuer', max_length=150)),
                ('issue_date', models.DateField(db_column='issue_date')),
                ('expiry_date', models.DateField(blank=True, db_column='expiry_date', null=True)),
                ('cred_id', models.CharField(blank=True, db_column='cred_id', max_length=100, null=True)),
                ('cred_url', models.TextField(blank=True, db_column='cred_url', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usercredentials_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('userinterests_id', models.AutoField(db_column='userinterests_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userinterests_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('userSkill_id', models.AutoField(db_column='userskills_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'userskills_tbl',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
