# Generated by Django 5.2.4 on 2025-09-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_genskill_specskill_usercredential_userinterest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usercredential',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userinterest',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userskill',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_column='verification_status', default='UNVERIFIED', max_length=20),
        ),
    ]
