# Generated by Django 5.2.4 on 2025-09-13 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_usercredential_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredential',
            name='genskills_id',
            field=models.ForeignKey(blank=True, db_column='genskills_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='accounts.genskill'),
        ),
        migrations.AddField(
            model_name='usercredential',
            name='specskills_id',
            field=models.ForeignKey(blank=True, db_column='specskills_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='accounts.specskill'),
        ),
        migrations.AddField(
            model_name='usercredential',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinterest',
            name='genSkills_id',
            field=models.ForeignKey(db_column='genskills_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.genskill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinterest',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userskill',
            name='specSkills',
            field=models.ForeignKey(db_column='specskills_id', default=1, on_delete=django.db.models.deletion.RESTRICT, to='accounts.specskill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'specSkills')},
        ),
    ]
