# Generated by Django 5.2.4 on 2025-09-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usercredential_genskills_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
    ]
