# Generated by Django 5.2.4 on 2025-09-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(blank=True, db_column='profilepic', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userVerifyId',
            field=models.FileField(blank=True, db_column='userverifyid', null=True, upload_to='user_verifications/'),
        ),
    ]
