# Generated by Django 5.2.4 on 2025-09-18 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_profilepic_alter_user_userverifyid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('tradereq_id', models.AutoField(db_column='tradereq_id', primary_key=True, serialize=False)),
                ('reqname', models.CharField(db_column='reqname', max_length=100)),
                ('skillprof', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('CERTIFIED', 'Certified')], db_column='skillprof', max_length=13, null=True)),
                ('modedel', models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('IN_PERSON', 'In Person'), ('HYBRID', 'Hybrid')], db_column='modedel', max_length=25, null=True)),
                ('reqtype', models.CharField(blank=True, choices=[('SERVICE', 'Service'), ('OUTPUT', 'Output'), ('PROJECT', 'Project')], db_column='reqtype', max_length=10, null=True)),
                ('contextpic', models.ImageField(blank=True, db_column='contextpic', null=True, upload_to='requestcontext_pics/')),
                ('reqbio', models.CharField(blank=True, db_column='reqbio', max_length=150, null=True)),
                ('reqdeadline', models.DateTimeField(blank=True, db_column='reqdeadline', null=True)),
                ('genSkills', models.ForeignKey(blank=True, db_column='genskills_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='accounts.genskill')),
                ('requester', models.ForeignKey(db_column='requester_id', on_delete=django.db.models.deletion.CASCADE, related_name='trade_requests_made', to=settings.AUTH_USER_MODEL)),
                ('responder', models.ForeignKey(blank=True, db_column='responder_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_requests_received', to=settings.AUTH_USER_MODEL)),
                ('specSkills', models.ForeignKey(blank=True, db_column='specskills_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='accounts.specskill')),
            ],
            options={
                'db_table': 'tradereq_tbl',
                'managed': True,
            },
        ),
    ]
