# Generated by Django 5.2.4 on 2025-09-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_traderequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderequest',
            name='genSkills',
        ),
        migrations.AddField(
            model_name='traderequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_column='status', default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='modedel',
            field=models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('ONSITE', 'Onsite'), ('HYBRID', 'Hybrid')], db_column='modedel', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='reqdeadline',
            field=models.DateField(blank=True, db_column='reqdeadline', null=True),
        ),
    ]
