# Generated by Django 5.2.4 on 2025-09-20 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_traderequest_genskills_traderequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderequest',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_column='status', max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='TradeInterest',
            fields=[
                ('trade_interests_id', models.AutoField(db_column='trade_interests_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('interested_user', models.ForeignKey(db_column='interested_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='trade_interests', to=settings.AUTH_USER_MODEL)),
                ('trade_request', models.ForeignKey(db_column='tradereq_id', on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='accounts.traderequest')),
            ],
            options={
                'db_table': 'trade_interests_tbl',
                'ordering': ['-created_at'],
                'managed': True,
                'unique_together': {('trade_request', 'interested_user')},
            },
        ),
    ]
