# Generated by Django 5.2.4 on 2025-09-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_traderequest_status_tradeinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeinterest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], db_column='status', default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_column='status', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
