# Generated by Django 5.2.4 on 2025-09-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_tradeinterest_status_alter_traderequest_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderequest',
            name='specSkills',
        ),
        migrations.AddField(
            model_name='traderequest',
            name='exchange',
            field=models.CharField(blank=True, db_column='exchangename', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_column='status', max_length=15, null=True),
        ),
    ]
