# Generated by Django 5.2.4 on 2025-09-21 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_traderequest_specskills_traderequest_exchange_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderequest',
            name='contextpic',
        ),
        migrations.RemoveField(
            model_name='traderequest',
            name='modedel',
        ),
        migrations.RemoveField(
            model_name='traderequest',
            name='reqbio',
        ),
        migrations.RemoveField(
            model_name='traderequest',
            name='reqtype',
        ),
        migrations.RemoveField(
            model_name='traderequest',
            name='skillprof',
        ),
        migrations.CreateModel(
            name='TradeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillprof', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('CERTIFIED', 'Certified')], db_column='skillprof', max_length=13, null=True)),
                ('modedel', models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('ONSITE', 'Onsite'), ('HYBRID', 'Hybrid')], db_column='modedel', max_length=25, null=True)),
                ('reqtype', models.CharField(blank=True, choices=[('SERVICE', 'Service'), ('OUTPUT', 'Output'), ('PROJECT', 'Project')], db_column='reqtype', max_length=35, null=True)),
                ('contextpic', models.ImageField(blank=True, db_column='contextpic', null=True, upload_to='requestcontext_pics/')),
                ('reqbio', models.CharField(blank=True, db_column='reqbio', max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('trade_request', models.ForeignKey(db_column='tradereq_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.traderequest')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trade_details_tbl',
                'managed': True,
                'unique_together': {('trade_request', 'user')},
            },
        ),
    ]
