# Generated by Django 5.2.4 on 2025-09-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_traderequest_contextpic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedetail',
            name='total_xp',
            field=models.IntegerField(blank=True, db_column='total_xp', default=0, null=True),
        ),
    ]
