# Generated by Django 5.2.4 on 2025-09-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_tradedetail_total_xp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradedetail',
            name='id',
        ),
        migrations.AddField(
            model_name='tradedetail',
            name='tradedetails_id',
            field=models.AutoField(db_column='tradedetails_id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='classified_category',
            field=models.CharField(blank=True, db_column='classifiedcategory', max_length=100, null=True),
        ),
    ]
