# Generated by Django 5.2.4 on 2025-09-22 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_evaluation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradeinterest',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='tradeinterest',
            name='evaluation_status',
            field=models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('rejected', 'Rejected')], db_column='evaluation_status', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradeinterest',
            name='interested_user',
            field=models.ForeignKey(db_column='interested_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tradeinterest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], db_column='status', default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='tradeinterest',
            name='trade_request',
            field=models.ForeignKey(db_column='tradereq_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.traderequest'),
        ),
    ]
