# Generated by Django 5.2.4 on 2025-09-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_tradeinterest_evaluation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', null=True),
        ),
    ]
