# Generated by Django 5.2.4 on 2025-09-23 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_evaluation_created_at_remove_evaluation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('tradehis_id', models.AutoField(db_column='tradehis_id', primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(blank=True, db_column='completed_at', null=True)),
                ('requester_proof', models.ImageField(blank=True, db_column='requester_proof', null=True, upload_to='trade_proofs/requester/')),
                ('responder_proof', models.ImageField(blank=True, db_column='responder_proof', null=True, upload_to='trade_proofs/responder/')),
                ('requester_proof_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_column='requester_proof_status', default='PENDING', max_length=20)),
                ('responder_proof_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_column='responder_proof_status', default='PENDING', max_length=20)),
                ('trade_request', models.ForeignKey(db_column='tradereq_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.traderequest')),
            ],
            options={
                'db_table': 'tradehis_tbl',
                'managed': True,
            },
        ),
    ]
