# Generated by Django 5.2.4 on 2025-09-25 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_tradehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_token_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReputationSystem',
            fields=[
                ('repsys_id', models.AutoField(db_column='repsys_id', primary_key=True, serialize=False)),
                ('rated_at', models.DateTimeField(auto_now_add=True, db_column='rated_at')),
                ('requester_starcount', models.IntegerField(blank=True, db_column='requester_starcount', null=True)),
                ('responder_starcount', models.IntegerField(blank=True, db_column='responder_starcount', null=True)),
                ('requester_rating_desc', models.CharField(blank=True, db_column='requester_rating_desc', max_length=500, null=True)),
                ('responder_rating_desc', models.CharField(blank=True, db_column='responder_rating_desc', max_length=500, null=True)),
                ('trade_request', models.ForeignKey(db_column='tradereq_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.traderequest')),
            ],
            options={
                'db_table': 'repsys_tbl',
                'managed': True,
            },
        ),
    ]
