# Generated by Django 5.2.4 on 2025-09-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_passwordresettoken_reputationsystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reputationsystem',
            name='rated_at',
        ),
        migrations.AddField(
            model_name='reputationsystem',
            name='requester_rated_at',
            field=models.DateTimeField(blank=True, db_column='requester_rated_at', null=True),
        ),
        migrations.AddField(
            model_name='reputationsystem',
            name='responder_rated_at',
            field=models.DateTimeField(blank=True, db_column='responder_rated_at', null=True),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='requester_rated',
            field=models.BooleanField(db_column='requester_rated', default=False),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='responder_rated',
            field=models.BooleanField(db_column='responder_rated', default=False),
        ),
    ]
