# Generated by Django 5.2.6 on 2025-09-29 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_reputationsystem_rated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='specskills_id',
            field=models.ForeignKey(blank=True, db_column='specskills_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.specskill'),
        ),
    ]
