services:
  # Django Backend Service
  - type: web
    name: expair-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "expair-backend.onrender.com"

  # Frontend Next.js Service  
  - type: web
    name: expair-frontend
    env: node
    plan: free
    region: oregon
    buildCommand: cd / && npm ci && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_API_URL
        value: https://expair-backend.onrender.com

